name: Build
on: [ push ]

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: windows-latest
    continue-on-error: true
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup | Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
          cache: true
          cache-key: 1b7869fe-c378-48bc-b913-fac1b676f9ab # change this to force refresh cache
      
      - name: Setup | Config
        run: flutter config --enable-windows-desktop
        
      - name: Build | Windows
        run: flutter build windows

      - name: Deploy | Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Annix
          path: |
            ./build/windows/runner/Release/
            
