name: Canary Release
on: push

jobs:
  iOS:
    runs-on: macos-latest
    env:
      KEYCHAIN: job-${{ github.job }}-${{ github.run_id	}}-${{ github.run_number }}-${{ github.run_attempt }}
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup | Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: ${{ secrets.FLUTTER_CACHE_KEY }}
      - name: Setup | Dependencies
        run: |
          rustup target add x86_64-apple-darwin aarch64-apple-darwin
          rustup update
          flutter pub get
      - name: Build | iOS
        run: |
          flutter build ios --no-codesign --verbose --build-number ${{ github.run_number }}
      - name: Deploy | Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: annix-ios
          path: ./build/ios/
          retention-days: 1

  publish:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: [ iOS ]
    runs-on: ubuntu-20.04
    env:
      GH_REPO: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y gettext-base

      - run: |
          (echo 'SUBJECT=Annix development (canary) build') >> $GITHUB_ENV
          gh release delete canary --yes || true
          git push origin :canary || true
      - name: Publish release
        run: |
          gh release create canary --prerelease --title "$SUBJECT" --target $GITHUB_SHA annix-android/*.apk annix-linux64/* annix-macos/* annix-win64/*
